### ISSUE TITLE
Mini Lover interaction

### ISSUE THREAD

**Issue by JeSuisUneLicorne** [Eisbison/TheOtherRoles#132]
The combination Child + Lover is possible. Please make this impossible for obvious reasons.

**Comment by Eisbison** [comment]
Please name the reasons ;) And please use a proper title for the issue....

**Comment by JeSuisUneLicorne** [comment]
K3ndo should have noticed you, Eisbison.

**Comment by Maryjane007** [comment]
??

**Comment by Eisbison** [comment]
A Child lose will be triggered, when the Lover mate gets voted out. We'll fix this with v2.6.7

**Comment by SinJin59** [comment]
But this makes sense? I don´t get the Problem. Logically everyone looses if the Child dies. and the Child dies if the Lover dies. Can someone explain me the Problem? I would prefer if you would make it an option, if the Child can be Lover or not.

**Comment by JeSuisUneLicorne** [comment]
Its not a voting / killing problem. Children shouldn't be part of a lover couple for obvious reasons. Think about reallife. This shouldn't get promoted on a game which every age class plays. Thanks for your understanding.

**Comment by Eisbison** [comment]
You're right, we didn't think of every case while developing it. We'll rename the child role with the next update.

**Comment by JeSuisUneLicorne** [comment]
No. Don't rename the child. Either rename the Lover of the Child to "Parent" or better: Just make it impossible for a child to be lover.

Thanks.

**Comment by SinJin59** [comment]
Sorry.... I understand what you want but this is in my opinion a bit too crazy. First thing: Kids under 18 need to have an adult besides them to play the game. Second thing: This is a GAME! Games are not the bad ones, just because people seeing something bad in it. The same argument you could use for Star Wars Battlefront or whatever Shooter. "Could you please use only fake projectiles. This is for obvious reassons not good with realistic projectiles" Just because it is for 16+? Srsly this is nutz.

**Comment by JeSuisUneLicorne** [comment]
LOL!
On what planet you live, bro? Ever saw a parent stay 8 hrs next to their kids to controll them? What should be done and what happens in reallife are two different things. We dont talk about Star Wars BF here - we talk about this mod. And for obvious reasons there shouldnt be a "child lover".

**Comment by Eisbison** [comment]
I'll release tge changes tomorrow. I'll rename the role, as I want to keep the interaction between the two roles in the game. That sgould resolve all the issues and everyone will be happy :)

**Comment by JeSuisUneLicorne** [comment]
Its your mod, Eisbison, but tbh I dont think that people like the new name. Also "Mini" is growing and when 18 is not Mini anymore. Its still a child. Its still the same problem from my point of view.  Why not make it impossible to be child/mini and lover at the same time? Just like its impossible to have a spy and a child at the same time? No renames needed.

**Comment by Eisbison** [comment]
The Spy thing has already been fixed with 2.6.7. It's not the same problem after the rename, because there's no more association to actual human beings so there's no more problem calling it a killing mini or loving mini. Something growing up and turning 18 doesn't automatically imply that... but I'll change it from calling it age and capping it at 18 to percent or somthing if people still think it's still a problem. People will get used to the name and the name has no impact anyways. And the interaction is not that bad, so I want to keep it such that the Lovers can have every role (and not just some).

**Comment by sihaack** [comment]
Damn that's so over sensitive it isn't even funny anymore.

It's a mod for a game.. That people would actually complain about names.. 🤦🏿‍♀️
