### ISSUE TITLE
add roles to freeplay so we can get imposter and crewmate roles 

### ISSUE THREAD

**Issue by balloplayz** [Eisbison/TheOtherRoles#137]
its fun when i get custom roles in freeplay please add roles to freeplay again or bad review

**Comment by SinJin59** [comment]
This is your argument? "Or bad review"? I think not that thats, an argument. Beside that, it is childish.

**Comment by Eisbison** [comment]
This issue is.... funny :D Roles will break the freeplay and it doesn't really make sense to test them there as you can't really interact properly with the dummies.... just start a local game with mutliple game instances. Also it's not worth the effort to implement somethign there, as local games work like a charm.
I'll close this issue here, as it isn't even an issue... :D

**Comment by balloplayz** [comment]
k sorry i just like freeplay mode so i dont have to open 4 different windows and get aggravated nvm great mod love it ebison role idea swooper turn invisible
