### ISSUE TITLE
Game End Bug

### ISSUE THREAD

**Issue by Scamper10** [Eisbison/TheOtherRoles#185]
EDIT: I think this happens if the host has multiple instances of the game open, and only effects the host's machine.

When the game ends (in any way) and the host is an imposter, the imposter(s) are not sent to the victory or defeat screen, rather they stay in the game as if it hadn't ended. They can't sabotage (except doors), the use button for admin, vitals, etc does not appear, and the kill button either doesn't cooldown or flashes when attempting to kill.

The other players can either quit or select play again and get the "Waiting for Host" message

This is fixed if the host leaves the game.

**Comment by soerface** [comment]
I've observed a similar thing while developing and running multiple instances. For the person who is the impostor, the game will not end. All other players receive a "defeat" screen. The symptoms for the impostor that is still in the game are the ones you described, additionally, timers won't count down anymore (probably because the host assumes that the game is finished).
