### ISSUE TITLE
Time Master Balance Request

### ISSUE THREAD

**Issue by techdude** [Eisbison/TheOtherRoles#188]
This is based off of gameplay observation, but right now the Time Master role appears to be slightly too weak. It's close, but the rewind time is too small given that it doesn't reset the kill cooldown. I think it can still work, but I believe a longer rewind time (timeMasterRewindTime) is needed.

When it pops, if it only rewinds 3 seconds (the current default) it's highly likely you will be in the same situation again (and in watching several games, this tends to be the case). I would consider the current maximum of 10 as a good new default as that increases the likelihood of being able to actually do something to change the outcome.

In addition, I think that the maximum time for the property should be increased to 30 seconds. This will allows various groups to play around with the value a bit and try to balance it. I suspect that the optimal value is somewhere between 10 and 20 seconds based on watching gameplay where it could potentially be used.

Summary of suggested changes:

- In CustomOptions.cs, update timeMasterRewindTime default to 10, min to 5, maximum to 30, and step to 5.

**Comment by Eisbison** [comment]
REgarding changing the default setting, I think everyone is capable of selecting something else than the default, hence I think we can leave that. Regarding increasing the maximum time: Theoretically a good idea, practically there's a reason why it's limited to 10. The reason being that e.g. you can rewind 10s after the game start, but what would you do then... With low CD settings you could rewind right after a meeting, which would put you in the position that you were standing right before the meeting (because among us only resets the player position when the meeting ends, if I remember correctly). Also I think that 10s is quite a long time in Among Us, which is hence the simplest but also a sufficient solution.
