### ISSUE TITLE
Problem with join lobby v3.1.0

### ISSUE THREAD

**Issue by ministerpl** [Eisbison/TheOtherRoles#238]
for 20 friends have update v3.1.0 - but only  me , Tomi, and deMonica have same problem: We have same version , make many installs re-install  , using steam,  scan for file inssue copy 3.0.0 make update to 3.1.0 - try copy 3.1.0  we try almost all and always we can not join to lobby : 

![v3 1 0 problem with join to game](https://user-images.githubusercontent.com/48459898/142250618-db29c760-842c-4a80-9c54-55c1c7d52edd.png)

**Comment by ministerpl** [comment]
Problem is when more than 8/15 join to the game

**Comment by dwd0tcom** [comment]
I think this is also fixed with 3.1.2. Can you confirm this?

**Comment by ministerpl** [comment]
nope it's not fixed

**Comment by Eisbison** [comment]
I think it's not a mod issue, even if it seems like one. The mod just kicks you from a lobby, if the host doesn't send you his mod version within 10 seconds. In your case, you're unable to join because of a different issue (probably one of the issues that the official Innersloth servers are facing right now, mostly when a  lot of people join a lobby). If you're stuck in the joining process, you'll never recieve the required info from the host and hence the mod will kick you after the 10 seconds. Does the same thing happen to you when you're not using the mod?

**Comment by ministerpl** [comment]
nope i can play  orignal among us 15ppl.

**Comment by basarama** [comment]
Friend has the same issue with the latest 3.2.1

**Comment by Eisbison** [comment]
Does 3.2.2 resolve the issue for you?

**Comment by Eisbison** [comment]
I think it does, otherwise please reopen the issue.

**Comment by ministerpl** [comment]
ok 3.2.2 fix it
