### ISSUE TITLE
Using custom region doesn't work.

### ISSUE THREAD

**Issue by A1whizkid** [Eisbison/TheOtherRoles#4]
Tried using the custom regions, but when I use the region, it redirects me to Asia. Any idea why?

**Comment by Eisbison** [comment]
Have you set a server in the configs?

**Comment by neomis** [comment]
I'm having a similar issue.  I have  the 2021.3.5 Impostor server running and it works with other mods that have CUSTOM region options.  When I use this mod and select CUSTOM after configuring it loads to a black screen where I can hear mouse hover noises but it never leaves the black screen.  When I escape out the Region become "strmissing" (or something similar).

**Comment by neomis** [comment]
So my issue was fixed by changing the Custom = Custom line to Custom = CUSTOM.  Now i have the same issue as @A1whizkid  where it redirects to Asia

**Comment by A1whizkid** [comment]
I have the Newest AU version and TOR version. My servers were pre-set, so idk what’s happening  :/

**Comment by neomis** [comment]
I'm guessing because I can't figure out how to test the plugin I just compiled (very new to this).  In you Main.cs you have
` new ServerInfo($"CustomServer", ip, Port.Value)`
Should `$"CustomServer"` be `Name.Value + "-Master-1"`
This is what I'm seeing other mods use for this section.

This might have nothing to do with why it's switching to Asia but its the only section of code I see dealing with CUSTOM servers.

**Comment by Eisbison** [comment]
I removed the Custom server code, such that you can add a 3rd party custom server client. Recommending you https://github.com/MoltenMods/Unify and closing this issue for now.
