### ISSUE TITLE
Libraries & projectfile missing

### ISSUE THREAD

**Issue by nokoji** [Eisbison/TheOtherRoles#55]
Related to #1

GPL requires you to provide all the source necessary to build the software, including supporting libraries, compilation scripts, and so on.

Based on the changelog this release is utilizing an "own implementation of reactor"
Where is the source? Also why was the project file removed?

**Comment by MrFawkes1337** [comment]
"An own implementation of Reactor"? What? have you actually looked at the source to see if you can find anything related to Reactor? Because I can guarantee it's not there. He completely removed the dependancies on Reactor and Essentials, and STILL provided the source, but you can't make everyone happy. You'll find the rest of the Supporting Library .DLL's in BepinEx/Core and BepinEx/Unhollowed, just copy and paste them into the folder and the errors will disappear :) 
[ProjectFile.zip](https://github.com/Eisbison/TheOtherRoles/files/6273725/ProjectFile.zip)
Open this with Notepad, take note of the .dll files mentioned at the bottom, and copy them to the folder with the .csproj, open the project file, job done. You can close this now :)

**Comment by nokoji** [comment]
Eisbison has already replied to this (on #1)

I agree it can be closed
