### ISSUE TITLE
some minor problems found while playing

### ISSUE THREAD

**Issue by ThaSiouL** [Eisbison/TheOtherRoles#9]
engineer gets timewarped out off vent -> game still counts it as in game? blocked from certain actions until the next meeting. 

child can't reach trash shoot on polus. -> seems to be an issue for all child mods. (both tested with and without "better polus") 
Maybe increasing the interaction range of children would help while not causing conflicts with map mods?

**Comment by Eisbison** [comment]
The first issue is being fixed with todays update, thanks for the report.

The second issue has not been fixed yet, but I am working on it. As the child now "grows up" with the new update, it eventually will be able to do all the tasks. It's not a fix, but it does the job for now. I will close the issue here if that's fine with you? Or should I wait until the complete fix is in the mod?

**Comment by ThaSiouL** [comment]
it's your repo, do it like you want. 😄 I was about to make another issue about engineer not being able to do certain tasks because he likes hopping into vents more but I saw that that was reported on the discord. Where would you like the reports more?
